### ISSUE TITLE
question translation

### ISSUE THREAD

**Issue by Sl0ter** [gabrielgaudreault/RandomThings#1]
Hallo 
i translated the mod to German and i want to ask if you would like to add the translation in the mod?
[de_de.txt](https://github.com/gabrielgaudreault/RandomThings/files/9252505/de_de.txt)
it just allowed to upload txt file. 
Just change from .txt to .json

**Comment by st0x0ef** [comment]
Thanks a lot, I will add it in the next update

**Comment by st0x0ef** [comment]
Your feature has been added in version 1.2.1

https://www.curseforge.com/minecraft/mc-mods/random-things-forge/files/3925274
